/*
    QueryConnector - Attach a query to a Calc document
    Copyright (C) 2013 Enrico Giuseppe Messina

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
package com.meserico.queryconnector;

import java.util.List;

/**
 *
 * @author Enrico Messina
 */
public class ODBCList extends JExtList {

    public enum Type {
        System,
        User
    }
    
    /**
     * Creates new form ODBCList
     */
    public ODBCList() {
        super();
        initComponents();
    }
    
    public void setType(Type type){
        try{
            List<String> dsn;
            if(type.equals(Type.System))
                dsn = ODBCNames.getSystemNames();
            else
                dsn = ODBCNames.getUserNames();
            for(String curDSN : dsn)
                this.addItem(curDSN);
        }catch(Exception ex){
            ExceptionDialog.show(this.getDialogAncestor(), ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
