#ifndef INCLUDED_COM_MESERICO_QUERYCONNECTORSERVICE_IDL
#define INCLUDED_COM_MESERICO_QUERYCONNECTORSERVICE_IDL

#include <XQueryConnectorService.idl>

module com {
    module meserico {
		module queryconnector {
			service QueryConnectorService: XQueryConnectorService;
		};
    };
};

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */