#ifndef INCLUDED_COM_MESERICO_XQUERYCONNECTORSERVICE_IDL
#define INCLUDED_COM_MESERICO_XQUERYCONNECTORSERVICE_IDL


/// com
module com {
    ///  meserico
    module meserico {
        interface XQueryConnectorService {
            void updateAll( [in] any aInstance );
			void silentUpdateAll( [in] any aInstance );
        };
    };
};

#endif